# Generated by Django 4.1.12 on 2024-02-29 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinfo",
            name="SequencingData_url",
            field=models.CharField(default="", max_length=200),
        ),
    ]
