# Generated by Django 4.1.12 on 2024-03-08 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_city"),
    ]

    operations = [
        migrations.DeleteModel(
            name="City",
        ),
        migrations.DeleteModel(
            name="PrettyNum",
        ),
        migrations.RemoveField(
            model_name="sequencingdata",
            name="user",
        ),
        migrations.DeleteModel(
            name="userInfo",
        ),
        migrations.DeleteModel(
            name="SequencingData",
        ),
    ]
