# Generated by Django 4.1.12 on 2024-03-11 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="rnaseq",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=32)),
                ("filepath", models.FileField(upload_to="rnaseq/")),
            ],
        ),
    ]
