# Generated by Django 4.1.12 on 2024-03-12 03:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("home", "0008_remove_rnaseq_filepath_rnaseq_file_path"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rnaseq",
            name="username",
        ),
        migrations.AddField(
            model_name="rnaseq",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="rnaseq",
            name="file_path",
            field=models.FileField(upload_to="rnaseq/"),
        ),
    ]
