# Generated by Django 4.1.12 on 2024-03-12 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0011_rnaseq_user_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rnaseq",
            name="file_path",
            field=models.FileField(
                max_length=128, upload_to="rnaseq/", verbose_name="文件路径"
            ),
        ),
    ]
